# Generated by Django 2.1.7 on 2019-06-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CirclipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_diameters', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tooling_diameters', models.DecimalField(decimal_places=2, max_digits=4)),
                ('circlip_width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('circlip_thickness', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tip_type', models.IntegerField()),
            ],
        ),
    ]
