# Generated by Django 2.1.7 on 2019-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlip', '0002_auto_20190610_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlipmodel',
            name='circlip_deformed_diameters',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='circlipmodel',
            name='circlip_deformed_radius',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
