# Generated by Django 2.1.7 on 2019-06-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circlip', '0003_auto_20190610_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlipmodel',
            name='circlip_deformed_radius',
        ),
    ]
