# Generated by Django 2.1.7 on 2019-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlip', '0006_auto_20190610_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlipmodel',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
